### ISSUE TITLE
[Backend][Study] 通用心得 - 增加「原主修科系」欄位

### ISSUE THREAD

**Issue by JiaAnTW** [JiaAnTW/NCKU_Trans#142]
## Description
在通用心得DB增加「原主修科系」欄位。
- 注意事項
    - 在之前實作管理學系、學院時，如果修改了學系/學院的名稱，轉輔心得中相同的名稱也會跟著被改變。通用心得也應該時做這個功能 https://github.com/JiaAnTW/NCKU_Trans/blob/5cc0aac9b95b200ac9377323182babecebeb269c/app/Http/Controllers/DepartmentCollege.php#L75-L101 
    - 「原主修科系」欄位和content、title應該在同一table內(下方為前端目前傳入`create`的方式)

![image](https://user-images.githubusercontent.com/39335864/156578485-41746ba4-b454-4cec-aa0b-3a16199b4878.png)

**Comment by yellow-hank** [comment]
@JiaAnTW 是不是要新增學的欄位？

**Comment by JiaAnTW** [comment]
@yellow-hank 目前在轉輔那邊的作法是會單獨把學院/學系的map傳給前端，再讓前端自己去比對心得裡的資訊。所以我想這邊應該可以照一樣的方式不用傳?或是看你有沒有甚麼想法

**Comment by yellow-hank** [comment]
@JiaAnTW 那我實作的方式比照轉輔那邊
