### ISSUE TITLE
[Backend][Study] 修正DB中記錄單一心得具備的類別的方式

### ISSUE THREAD

**Issue by JiaAnTW** [JiaAnTW/NCKU_Trans#143]
## Description
目前在DB中記錄單一心得具備的類別的方式怪怪的，應該要有這兩個欄位
https://www.figma.com/file/jb0DTXJQbNBGK1h9XMCIbh/nckustudy%E8%B3%87%E6%96%99%E5%BA%AB%E8%A8%8E%E8%AB%96?node-id=0%3A1

![image](https://user-images.githubusercontent.com/39335864/156922175-1b56699b-f366-407c-8a15-bccea99afda9.png)

**Comment by yellow-hank** [comment]
@JiaAnTW 這個部分因為資料庫欄位不能有陣列的選項，所以將關係記錄在 category 和 statistic 的表格中，會在取得 study 時，變成陣列存在 json 中。
