### ISSUE TITLE
[Backend] updateCollege update the wrong column in Comments table

### ISSUE THREAD

**Issue by yellow-hank** [JiaAnTW/NCKU_Trans#160]
## Description
In line 84, it shouldn't update out_maj.
## Screenshot(if this is a bug)
https://github.com/JiaAnTW/NCKU_Trans/blob/0fa95e4c7b8e42d02545b0902a750699ed7d446f/app/Http/Controllers/DepartmentCollege.php#L74-L87

**Comment by yellow-hank** [comment]
@JiaAnTW 我在新的 commit 修正

**Comment by JiaAnTW** [comment]
@yellow-hank 轉出科系有機會會是學院/其他(為了預防有人不想透漏身分)，所以這裡還是要更新

**Comment by yellow-hank** [comment]
了解
