### ISSUE TITLE
[QA] 分享心得第一步驟按下返回會進入空白頁面

### ISSUE THREAD

**Issue by yungshenglu** [JiaAnTW/NCKU_Trans#31]
## Description

分享心得第一步驟按下返回會進入空白頁面，建議第一步驟可以不用「返回」

## Reproduce

1. 點擊側邊選單
2. 點擊「我要分享」進入「分享心得」畫面
3. 點擊「返回」後會進入「空白頁面」

## Screenshots

https://user-images.githubusercontent.com/11289171/129052388-6d8fded8-a040-4acf-b935-8405d0fecbc3.mp4

## Platform

- macOS Big Sur v11.2.3 
    - Chrome v91.0.4472.114 (Official Build) (x86_64)
    - Safari version 14.0.3 (16610.4.3.1.7)
- iPhone 11 Pro iOS 14.6
    - Chrome v92.0.4515.90
    - Safari

**Comment by JiaAnTW** [comment]
Fixed in commit https://github.com/JiaAnTW/NCKU_Trans/commit/7b0294a97f8e45513004458e9032000c3226f835 .
