### ISSUE TITLE
[Design] 分享心得的進度條都是勾勾無法區分是否完成

### ISSUE THREAD

**Issue by yungshenglu** [JiaAnTW/NCKU_Trans#32]
## Reproduce

1. 點擊左上角的選單按鈕
2. 點擊「我要分享」進入「分享心得」畫面
3. 點擊「下一步」並觀察上方進度條

## Screenshots

<img width="1078" alt="Screen Shot 2021-08-11 at 22 56 15" src="https://user-images.githubusercontent.com/11289171/129053024-1bcc5bd8-05e1-4f14-b94f-44eb1fb19312.png">

**Comment by Kyl23** [comment]
這裡之前有改過
https://github.com/Kyl23/NCKU_Trans/blob/32130bdd61bb86cd9e1253f513af4fc60daf9d82/resources/assets/js/components/Form/StepArea/index.js#L32-L61
