### ISSUE TITLE
[QA] 全部年份以外的「通過率(官方數據)」會無法呈現

### ISSUE THREAD

**Issue by yungshenglu** [JiaAnTW/NCKU_Trans#33]
## Reproduce

1. 進入「轉系/輔系/雙主修心得」頁面
2. 點擊「年份」下拉選單並選取「全部年份」以外的各個年份
3. 觀察畫面上的「通過率(官方數據)」

## Screenshots

<img width="1253" alt="Screen Shot 2021-08-11 at 23 13 26" src="https://user-images.githubusercontent.com/11289171/129055684-bd6c2a67-2d2b-4d8e-98c9-af3feeaf7166.png">
<img width="1215" alt="Screen Shot 2021-08-11 at 23 13 37" src="https://user-images.githubusercontent.com/11289171/129055696-e688404f-c512-4e33-b00b-ca2a43b34120.png">
<img width="1218" alt="Screen Shot 2021-08-11 at 23 13 49" src="https://user-images.githubusercontent.com/11289171/129055699-a2987128-0d51-4806-8858-6b538d0b36d7.png">

## Platform

- macOS Big Sur v11.2.3
    - Chrome v91.0.4472.114 (Official Build) (x86_64)
    - Safari version 14.0.3 (16610.4.3.1.7)
- iPhone 11 Pro iOS 14.6
    - Chrome v92.0.4515.90
    - Safari

**Comment by JiaAnTW** [comment]
這個是因為110年份是沒有資料的，timeout之後google app script會回傳錯誤，顯示無資料。

但有可能是request counter一直沒歸零所以才會無限轉圈，當backlog

**Comment by JiaAnTW** [comment]
fixed in commit https://github.com/JiaAnTW/NCKU_Trans/commit/7a7e32c9d6ef4413996c49080040a850f2dea31f
