### ISSUE TITLE
[QA] 不論選取那一種類別的「通過率(官方數據)」

### ISSUE THREAD

**Issue by yungshenglu** [JiaAnTW/NCKU_Trans#34]
## Reproduce

1. 進入「轉系/輔系/雙主修心得」頁面
2. 點擊「類別」下拉選單並選取每一種類別
3. 觀察畫面上的「通過率(官方數據)」

## Screenshots

<img width="1214" alt="Screen Shot 2021-08-11 at 23 29 43" src="https://user-images.githubusercontent.com/11289171/129059267-5cf4fa76-bd8c-493a-9630-6485d69c046f.png">
<img width="1206" alt="Screen Shot 2021-08-11 at 23 29 51" src="https://user-images.githubusercontent.com/11289171/129059281-4d5dc9d1-657f-4e61-9bc9-2cb16dd63395.png">
<img width="1232" alt="Screen Shot 2021-08-11 at 23 29 58" src="https://user-images.githubusercontent.com/11289171/129059288-a0f8b396-2f3c-42a6-831b-6906b07e05ed.png">
<img width="1232" alt="Screen Shot 2021-08-11 at 23 30 06" src="https://user-images.githubusercontent.com/11289171/129059296-fea40d52-fe4d-4f19-97e1-14cef90ee41b.png">

## Platform

- macOS Big Sur v11.2.3
    - Chrome v91.0.4472.114 (Official Build) (x86_64)
    - Safari version 14.0.3 (16610.4.3.1.7)
- iPhone 11 Pro iOS 14.6
    - Chrome v92.0.4515.90
    - Safari

**Comment by yungshenglu** [comment]
## Reproduce


## Screenshots


## Platform

**Comment by JiaAnTW** [comment]
這個原因是雙主跟輔修是沒有這個資料的，應該要把這兩個類別擋下來

**Comment by JiaAnTW** [comment]
fixed in commit https://github.com/JiaAnTW/NCKU_Trans/commit/7a7e32c9d6ef4413996c49080040a850f2dea31f
