### ISSUE TITLE
[Design] 心得內容彈窗的內容寬度可以拉寬

### ISSUE THREAD

**Issue by yungshenglu** [JiaAnTW/NCKU_Trans#35]
## Reproduce

1. 進入「轉系/輔系/雙主修心得」頁面
2. 點擊任一篇心得區塊會出現心得內容彈窗
3. 觀察畫面

## Screenshots

<img width="325" alt="Screen Shot 2021-08-11 at 23 41 54" src="https://user-images.githubusercontent.com/11289171/129060796-ec7e8eb0-ba8e-4097-9cb2-9b83193e8555.png">

**Comment by JiaAnTW** [comment]
手機版不拉寬是因為左右有一個切換文章的btn，怕不好操作
電腦版 & 平板都已經拉寬，可參考: https://github.com/JiaAnTW/NCKU_Trans/commit/cf803bfb434e5e2d309ba02cd890d3c9335d2a52
