### ISSUE TITLE
[Frontend][study] 通用學業心得 - 文章閱讀器

### ISSUE THREAD

**Issue by JiaAnTW** [JiaAnTW/NCKU_Trans#44]
## Description
- 做一個專屬學業心得的閱讀器(**不要修改舊的轉輔心得閱讀器**)
- 「編輯**類別**」可以先不用做UI，預留空間就好，這裡應該可以重複利用 https://github.com/JiaAnTW/NCKU_Trans/issues/42 的元件。
- 左右兩側切換文章的按鈕，實際上**可以點選的高度應該要和整個閱讀器一樣高**。
- 在後臺點選編輯時，應該要跳轉到心得表單頁面，且自動填入該心得原有的資料(仍然是修改該心得，並不是新增新心得。需要等 https://github.com/JiaAnTW/NCKU_Trans/issues/46 完成)。
### 前台
- prototype: 
    - [PC版link](https://www.figma.com/proto/Cf0I6JZmwyZBFpbv97YFCn/%E6%88%90%E5%A4%A7%E8%BD%89%E7%B3%BB%E7%94%9F%E5%BF%83%E5%BE%97%E5%B9%B3%E5%8F%B0?node-id=511%3A713&scaling=scale-down&page-id=511%3A702&starting-point-node-id=511%3A713&show-proto-sidebar=1)
    - [Mobile版link](https://www.figma.com/proto/Cf0I6JZmwyZBFpbv97YFCn/%E6%88%90%E5%A4%A7%E8%BD%89%E7%B3%BB%E7%94%9F%E5%BF%83%E5%BE%97%E5%B9%B3%E5%8F%B0?node-id=843%3A14804&starting-point-node-id=838%3A12892)
- spec(css參考): 
    - [PC版link](https://www.figma.com/file/Cf0I6JZmwyZBFpbv97YFCn/%E6%88%90%E5%A4%A7%E8%BD%89%E7%B3%BB%E7%94%9F%E5%BF%83%E5%BE%97%E5%B9%B3%E5%8F%B0?node-id=511%3A702)
    - [Mobile版link](https://www.figma.com/file/Cf0I6JZmwyZBFpbv97YFCn/%E6%88%90%E5%A4%A7%E8%BD%89%E7%B3%BB%E7%94%9F%E5%BF%83%E5%BE%97%E5%B9%B3%E5%8F%B0?node-id=843%3A14804)
- screen shot: 
  ![image](https://user-images.githubusercontent.com/39335864/147847490-5268aa7d-052c-46b6-8e3f-7e9a63d4be10.png)
  ![image](https://user-images.githubusercontent.com/39335864/149614456-c245f96f-3ef0-4e4f-8f99-5f337880793e.png)

### 後台
- prototype: [link](https://www.figma.com/proto/Cf0I6JZmwyZBFpbv97YFCn/%E6%88%90%E5%A4%A7%E8%BD%89%E7%B3%BB%E7%94%9F%E5%BF%83%E5%BE%97%E5%B9%B3%E5%8F%B0?node-id=652%3A3052&scaling=scale-down&page-id=511%3A702&starting-point-node-id=652%3A3052&show-proto-sidebar=1)
- spec(css參考): [link](https://www.figma.com/file/Cf0I6JZmwyZBFpbv97YFCn/%E6%88%90%E5%A4%A7%E8%BD%89%E7%B3%BB%E7%94%9F%E5%BF%83%E5%BE%97%E5%B9%B3%E5%8F%B0?node-id=511%3A702)
- screen shot: 
![image](https://user-images.githubusercontent.com/39335864/147847529-de6c7071-5ed9-48da-b1f5-fb6307e1ddd8.png)
![image](https://user-images.githubusercontent.com/39335864/147847521-5ca02566-9ecd-4725-b1a5-9d5263290a55.png)

**Comment by JiaAnTW** [comment]
@vacantron 搜尋元件結束後下一個會想請你幫忙這個，有問題可以先在這張issue再問我，感謝!

**Comment by vacantron** [comment]
中間的數據資料應該可以拆開成獨立的component，主頁面也用得到。
