### ISSUE TITLE
[Frontend] 通用學業心得 - 資料流

### ISSUE THREAD

**Issue by JiaAnTW** [JiaAnTW/NCKU_Trans#47]
- 串接後端
- Redux中的study資料流處理。應該要包含

action          | 說明  | 
--------------|:-----:|
SET_STUDY_FILTER     | 設定study文章的篩選統計條件
CLEAR_STUDY_FILTER  | 清除所有study文章的篩選統計條件
ADD_STUDY_STAT     | 新增統計項目(後台)
UPDATE_STUDY_STAT     | 更新已存在的統計項目(後台)
DELETE_STUDY_STAT     | 刪除已存在的篩選項目(後台)

## 後端API資訊
- [分類項目](https://github.com/JiaAnTW/NCKU_Trans/wiki/Backend#apigetstudytype-%E5%8F%96%E5%BE%97%E6%89%80%E6%9C%89%E5%88%86%E9%A1%9E%E9%A0%85%E7%9B%AE)
- [統計資料](https://github.com/JiaAnTW/NCKU_Trans/wiki/Backend#apigetstudystat-%E5%8F%96%E5%BE%97%E6%89%80%E6%9C%89%E7%B5%B1%E8%A8%88%E8%B3%87%E6%96%99)

**Comment by fung-hei-man** [comment]
Update needed Redux Actions and their meaning

action          | 說明  | 
--------------|:-----:|
SET_STUDY_FILTER     | 設定study文章的篩選統計條件
CLEAR_STUDY_FILTER  | 清除所有study文章的篩選統計條件
INIT_STUDY_STAT  | 從backend取得統計&分類頂目並加到store
ADD_STUDY_STAT     | 新增統計&分類項目(後台)
UPDATE_STUDY_STAT     | 更新已存在的統計&分類項目(後台)
DELETE_STUDY_STAT     | 刪除已存在的統計&分類項目(後台)
