### ISSUE TITLE
分離進入頁面的component

### ISSUE THREAD

**Issue by JiaAnTW** [JiaAnTW/NCKU_Trans#63]
## Description
現在FE進入每個頁面幾乎都會先預設顯示loading，等request都結束再顯示一般頁面。

請將這個行為分離成共用component。

**Comment by vacantron** [comment]
這裡是單純的把重複的https://github.com/JiaAnTW/NCKU_Trans/blob/5cc0aac9b95b200ac9377323182babecebeb269c/resources/assets/js/page/Major/index.js#L17-L23
重構成可以重用的FC對嗎？還是要連hook也一起重構？

**Comment by JiaAnTW** [comment]
@vacantron 對，這個issue的scope是把「根據request數量判斷是否顯示Loading」的邏輯拉出來變共用UI component。useInitData每個頁面都不一樣，所以目前沒有要重構
