### ISSUE TITLE
[Backend][study] 實作通用心得DB table的CRUD

### ISSUE THREAD

**Issue by JiaAnTW** [JiaAnTW/NCKU_Trans#78]
## Description
在 https://github.com/JiaAnTW/NCKU_Trans/issues/77 後。實作DB的CRUD。最後應該要提供以下API:

url          | method | params  |  authentication  | 說明 | 目前進度
--------------|:-----:|:-----:|:-----:|:-----:|:-----:|
`/api/get/study?from={id}&num={num}`    | GET | - |   | 回傳  confirm equal true 從id為`{id}`的心得以前`{num}`筆心得資料。若少於`{num}`筆則剩下的全部回傳。| V
`/api/get/study/all?from={id}&num={num}`    | GET | - | V  | 回傳從id為`{id}`的心得以前`{num}`筆心得資料。若少於`{num}`筆則剩下的全部回傳。| V
`/api/post/study` | POST   | 同study心得schema   |     | 新增一筆study心得資料 | V
`/api/patch/study?id={id}` | PATCH  | confirm: `true/false`  | V  | 更新id為`{id}`的心得的confirm | V
`/api/post/study?id={id}`    | UPDATE  | 同study心得schema  | V  | 更新id為`{id}`的心得的所有資料 | V
`/api/delete/study?id={id}`    | DELETE  | -  |  V  | 刪除id為`{id}`的心得 | V
`/api/get/studyType` | GET   | TBD   |     | 取得所有study**類別** | V
`/api/post/studyType` | POST   | TBD   |     | 新增一個新的study**類別** | V
`/api/post/studyType?id={id}`    | UPDATE  | TBD   | V  | 更新id為`{id}`的study**類別** | V
`/api/delete/studyType?id={id}`    | DELETE  | -  |  V  | 刪除id為`{id}`的study**類別** | V
`/api/get/studyStat` | GET   | TBD   |     | 取得所有study**項目** |  V
`/api/post/studyStat` | POST   | TBD   |     | 新增一個新的study**統計項目** | V
`/api/post/studyStat?id={id}`    | UPDATE  | TBD   | V  | 更新id為`{id}`的study**統計項目** | V
`/api/delete/studyStat?id={id}`    | DELETE  | -  |  V  | 刪除id為`{id}`的study**統計項目** | V

**Comment by JiaAnTW** [comment]
@yellow-hank 注意時區問題

**Comment by JiaAnTW** [comment]
@yellow-hank 這邊有個新需求給填寫新心得用，再麻煩你幫忙想想看怎麼實作比較好，感謝!
1. 需要有回傳所有可填寫的統計項目的API
2. 這個API需要回傳一個可以讓前端排序用的東西(可能是id然後用流水號之類的)

**Comment by yellow-hank** [comment]
了解

**Comment by yellow-hank** [comment]
@JiaAnTW studyType 應該要有一個 api 回傳現在所有的分類項目

**Comment by JiaAnTW** [comment]
@yellow-hank 感謝提醒，想了一下統計項目應該也要有，因為心得改成回傳前幾筆了

**Comment by JiaAnTW** [comment]
統計數據字串最多10個字

**Comment by JiaAnTW** [comment]
@yellow-hank 那這個`從第N個開始`的N前端這邊要怎麼產生，我想到的是可能有有新心得但前端還沒更新，這樣有機會會出錯

**Comment by yellow-hank** [comment]
@JiaAnTW N 設為零來取最新的值，接續後面的N 就看要取哪個段落來決定
